# Generated by Django 4.1.1 on 2024-04-22 02:56

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dpi',
            field=models.BigIntegerField(validators=[usuario.models.validate_dpi_length]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(validators=[usuario.models.validate_telefono_length]),
        ),
    ]
